import { Menu } from "@/components/Global/Menu";
import "./globals.css";
import type { Metadata } from "next";
import MenuLeft from "@/components/Global/MenuLeft";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans flex w-screen h-screen text-slate-700`}>
        <MenuLeft />
        <div className="grow">
          <Menu />
          {children}
        </div>
      </body>
    </html>
  );
}
