import { Menu } from "@/components/Global/Menu";
import "./globals.css";
import type { Metadata } from "next";
import MenuLeft from "@/components/Global/MenuLeft";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-siliguri max-w-1080p m-auto max-h-[1000px] flex w-screen h-screen text-slate-700 overflow-hidden">
        <header>
          <MenuLeft />
        </header>
        <main className="flex flex-col grow relative">
          <Menu />
          {children}
        </main>
      </body>
    </html>
  );
}
