import { Menu } from "@/components/Global/Menu";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MenuLeft from "@/components/Global/MenuLeft";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex w-screen h-screen`}>
        <MenuLeft />
        <div className="grow">
          <Menu />
          {children}
        </div>
      </body>
    </html>
  );
}
